import { StyleSheet } from 'react-native';

export const foodHomeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FAFAFA',
  },
  container: {
    paddingTop: 10,
    paddingBottom: 40,
    paddingHorizontal: 25,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 25,
  },
  avatar: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
  },
  titleContainer: {
    marginBottom: 30,
  },
  subtitle: {
    fontSize: 18,
    color: '#666',
    fontWeight: '400',
  },
  title: {
    fontSize: 34,
    fontWeight: '800',
    color: '#333',
    lineHeight: 40,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 35,
  },
  searchIconContainer: {
    marginRight: 10,
    paddingBottom: 8,
  },
  searchInputContainer: {
    flex: 1,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    paddingBottom: 8,
  },
  searchInput: {
    fontSize: 16,
    color: '#333',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#333',
    marginBottom: 20,
  },
  categoriesList: {
    paddingRight: 20,
    marginBottom: 35,
  },
  categoryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 25,
    padding: 20,
    marginRight: 15,
    alignItems: 'center',
    width: 110,
    height: 175,
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  categoryCardActive: {
    backgroundColor: '#F6CA45',
  },
  categoryIconContainer: {
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#666',
  },
  categoryNameActive: {
    color: '#333',
  },
  categoryArrowBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  arrowActiveBg: {
    backgroundColor: '#FFF',
  },
  arrowInactiveBg: {
    backgroundColor: '#F06E66',
  },
  popularCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 25,
    padding: 20,
    marginBottom: 20,
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    minHeight: 160,
    overflow: 'hidden',
  },
  popularInfo: {
    flex: 1,
    zIndex: 2,
  },
  topWeekContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  topWeekText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#333',
    marginLeft: 8,
  },
  popularName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
    marginBottom: 5,
  },
  popularWeight: {
    fontSize: 13,
    color: '#999',
    marginBottom: 20,
  },
  popularBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 'auto',
  },
  addButton: {
    backgroundColor: '#F6CA45',
    width: 75,
    height: 50,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 8,
    borderTopLeftRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 20,
    marginLeft: -20,
    marginBottom: -20,
    borderBottomStartRadius: 25,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#333',
    marginLeft: 6,
  },
  popularImage: {
    width: 180,
    height: 160,
    position: 'absolute',
    right: -20,
    bottom: -10,
    resizeMode: 'contain',
    zIndex: 1,
  },
});
