import { StyleSheet } from 'react-native';

export const foodDetailsStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FAFAFA',
  },
  container: {
    paddingTop: 10,
    paddingBottom: 100,
    paddingHorizontal: 25,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
  },
  backButton: {
    width: 45,
    height: 45,
    borderRadius: 12,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#EAEAEA',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  favButton: {
    width: 45,
    height: 45,
    borderRadius: 12,
    backgroundColor: '#F6CA45',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#F6CA45',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  title: {
    fontSize: 36,
    fontWeight: '800',
    color: '#333',
    width: '60%',
    lineHeight: 42,
    marginBottom: 10,
  },
  price: {
    fontSize: 32,
    fontWeight: '700',
    color: '#F06E66',
    marginBottom: 30,
  },
  middleSection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 40,
    position: 'relative',
  },
  infoCol: {
    flex: 1,
    zIndex: 2,
  },
  infoBlock: {
    marginBottom: 20,
  },
  infoLabel: {
    fontSize: 14,
    color: '#999',
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333',
  },
  imageCol: {
    position: 'absolute',
    right: -100,
    top: -20,
    zIndex: 1,
  },
  productImage: {
    width: 310,
    height: 270,
    resizeMode: 'contain',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#333',
    marginBottom: 15,
  },
  ingredientsList: {
    paddingRight: 20,
    paddingBottom: 20, 
    paddingTop: 10,
    paddingLeft: 5,
  },
  ingredientCard: {
    width: 100,
    height: 90,
    backgroundColor: '#FFF',
    borderRadius: 20,
    marginRight: 15,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    margin: 4,
  },
  ingredientColorBlock: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ingredientInitial: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFF',
  },
  bottomBar: {
    position: 'absolute',
    bottom: 40,
    left: 25,
    right: 25,
  },
  orderButton: {
    backgroundColor: '#F6CA45',
    flexDirection: 'row',
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#F6CA45',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 5,
  },
  orderButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
    marginRight: 8,
  }
});
